FNA-XNA/FAudio

- src/F3DAudio.c
- src/FAudio_internal.c
Fixed isnan + strange build errors in FAudio_internal
> Fix for VS 2010 build

- cpp/xaudio2.cpp
- csharp/FAudio.cs
- src/FAudio.c
- src/FAudio.h
- src/FAudioFX.c
- src/FAudio_internal.c
- src/FAudio_internal.h
These changes are motivated by getting FAudio to build in Wine's build system, and fixing a few of the problems that Wine's tests turned up.
In particular, I think "Update FAudioVoiceDetails" and "Advance buffer offset" need careful review, as they're significant changes that could impact existing clients.
More to come ;)
> Wine fixes

- Makefile
To create any missing sub-dirs.
> Install with 'install -D'

- README
> Add iOS/tvOS info to README

- tests/Makefile
- tests/xaudio2.c
Add tests showing recent changes match Windows behavior.
> OnVoiceProcessingPassStart tests

- src/FAudio_ffmpeg.c
Just merging these two as they look fine to me - it's certainly better than my version of the reverse seeking problem!
> Johan's FFmpeg fixes

- src/F3DAudio.c
- src/F3DAudio.h
- src/FACT.c
- src/FACT.h
- src/FACT3D.c
- src/FACT3D.h
- src/FACT_internal.c
- src/FACT_internal.h
- src/FAPO.h
- src/FAPOBase.c
- src/FAPOBase.h
- src/FAPOFX.c
- src/FAPOFX.h
- src/FAPOFX_echo.c
- src/FAPOFX_eq.c
- src/FAPOFX_masteringlimiter.c
- src/FAPOFX_reverb.c
- src/FAudio.c
- src/FAudio.h
- src/FAudioFX.h
- src/FAudioFX_reverb.c
- src/FAudioFX_volumemeter.c
- src/FAudio_ffmpeg.c
- src/FAudio_internal.c
- src/FAudio_internal.h
- src/FAudio_internal_simd.c
- src/FAudio_platform_sdl2.c
- src/XNA_Song.c
I understand if this is closed with "no, go away" :)
> Add vim modelines

- CMakeLists.txt
- cmake/modules/FindFFmpeg.cmake
add ffmpeg script and link to FAudio if needed
> cmake: add FFMPEG find script

- CMakeLists.txt
- cmake/modules/FindFFmpeg.cmake
tested with x86_64-mingw-w64 on Arch linux
but the Tools subdir won't build for me on mingw. And I don't know how to build the wine cpp wrappers under linux
> cmake: add cpp wrapper

- src/FAudio.c
- tests/FAudio_compat.h
- tests/xaudio2.c
File under "how did this ever work?"
> Valgrind fixes

- cmake/install_shared_libs.cmake
- additionally search in lib subfolder for library
- recognize *.lib libraries as static lib
> cmake: install_shared: also search lib dir

- src/FAudio_operationset.c
> one more extraneous semicolon

- src/FACT_internal.c
use an unsigned integer for index variable
and fix -Wsign-compare warning
> internal: use unsigned for index variable

- include/FACT.h
- src/FACT_internal.h
- src/FAudio_internal.h
using __extension__ keyword
Found solution at: https://stackoverflow.com/a/20345704
https://github.com/FNA-XNA/FAudio/issues/144
> silence pedantic warnings for unnamed union and structs

- src/FAudio_internal.h
- src/FAudio_platform_sdl2.c
add asserts for pointer variables for WriteWaveFormatExtensible and FAudio_PlatformInit functions
> More asserts for pointer

- utils/testxwma/testxwma.cpp
When a file with a fmt chunkSize > 40 (size of FAudioWaveFormatExtensible struct)
was processed a buffer overflow occured potentially corrupting memory.
> testxwma: fix buffer overflow

- src/FACT.c
As per issue I asked about, removing the unrequired if.
> Remove unrequired check

- src/FAudio.c
- use format "XWMA" instead of "WAVE"
- set cbSize to 0
> dump: special handling for WMAUDIO2

- src/FACT_internal.c
Game: Drakensang - The River of Time.
> Support content type 45 for AudioEninge/SoundBank/WaveBank

- csharp/FAudio.cs
Round two.  I'm open to ideas to streamline the API. Unfortunately the buffer alloc has to be exposed as a separte step (as far as I know).
> Avoid string and byte[] allocation when converting to UTF8 native string

- src/FAudioFX_reverb.c
- visualc-winrt/README
- visualc/FAudio.sln
- visualc/README
- visualc/testparse/testparse.vcxproj
- visualc/uicommon/uicommon.vcxproj
Compile fix in FAudioFX_reverb.c, various project build fixes, README copy-paste corrections
> VS2010 Fixes

- src/FACT.c
> Close the Wavebank IO only when not streaming

- src/FAudio_internal.c
> Process filters and effects despite empty send list

- src/FACT_internal.c
- src/FACT_internal.h
Verified using CastleMiner Z for X360 and for PC.
> More X360 content endianness fixes

- CMakeLists.txt
- cmake/FAudio.pc.in
- src/FAudio.c
- src/FAudio_gstreamer.c
- src/FAudio_internal.c
- src/FAudio_internal.h
- src/FAudio_platform_sdl2.c
- src/FAudio_platform_win32.c
- src/stb.h
As discussed in https://github.com/FNA-XNA/FAudio/pull/252 this is going to be useful for Wine.
> Add a native Win32 platform implementation. 

- CMakeLists.txt
Fixes https://github.com/FNA-XNA/FAudio/issues/259
> fixed cmake config name

- src/FAudioFX_reverb.c
This is required by Rez Infinite, see #225. I'm pretty sure I got all of the places where channel counts are used, but please double-check, and also look over my usage of the internal reverb API.
As always, feel free to fixup any style issues in this commit.
> Support 5p1 -> 5p1 reverb

- src/FAudio_platform_win32.c
Instead of asserting on errors, we can handle them and play silence instead, some errors are not completely unlikely.
The change in Wine-Mono FNA to use the Win32 platform caused a regression when running with upstream Wine, which doesn't have the WMA Decoder MF transform yet. This should get back to the old behavior in that case where silence was played.
> Better handle win32 WMADEC init and decode errors.

- src/FAudio_internal_simd.c
Matching SDL
https://github.com/libsdl-org/SDL/blob/main/src/audio/SDL_audiotypecvt.c#L933
> Fix 8-bit audio conversion on ARM platforms

- visualc-gdk/FAudio.sln
- visualc-gdk/FAudio.vcxproj
The project only targets the Xbox platforms, since I couldn't think of any reason to make a GDK-specific build of FAudio for regular Windows desktop.
> Add visualc-gdk solution

- src/qoa_decoder.h
> Remove bogus variable expression

- src/FACT.c
- src/FACT_internal.c
This will stop the crash in #336 .
> Support cues which have no variation

- src/FAudio_platform_sdl3.c
fixed up some SDL 3 renamed symbols
> fixed renamed symbols on SDL3 backend

- src/FAudio_internal.h
Macro has been renamed in https://github.com/libsdl-org/SDL/commit/32907a96069c6a8084964fddf9ed793d8cf5dc95
> SDL3: Updated to latest SDL3 version.

- .github/workflows/ci.yml
Adds PPC32 Artifacts, the container is based on Debian 12, I hope that's fine.
> PowerPC Artifacts

- .github/workflows/ci.yml
It's not clang, ignore the branch name.
> MSVC CI SDL3

- src/FAudio.c
I have a game that submits garbage data and crashes. My Ad-hoc testing shows that Xaudio2.8 and 2.9 validate the length, but XAudio2.7 does not. I tried to write tests, but I ran into multiple issues with tests/xaudio2.c and the file doesn't seem to be touched since 5 years.
---
List of issues with the tests from memory:
* IXAudio27 don't exist any more in modern Wine headers. Wine 8.0 has them though.
* Xaudio2.8 doesn't detect any devices, GetDeviceCount returns garbage. AFAIU it isn't supposed to be used for 2.8 and newer.
* If I hack around that, IXAudio2MasteringVoice::SetEffectChain crashes.
* If I disable that, IXAudio2SourceVoice::GetState crashes on xaudio2.8.
At that point I gave up and decided to submit this without tests.
> Validate PlayBegin+PlayLength against AudioBytes.

- .github/workflows/ci.yml
This was added to the SDK README recently, but the image isn't live AFAICT.
CC @Fancy2209
> CI: Add Sniper AArch64 workflow

- src/FAudio.c
My patch c00b01caa6e3f0dce09af6676ff55936e97b451c ("Don't destroy voice when it is output to other voices") technically caused a regression with some games under Wine reported here: https://bugs.winehq.org/show_bug.cgi?id=58253
The blamed  commit still looks correct though, the actual problem is elsewhere.
The game first create a source voice without pSends (which is correctly linked to mastering voice) and then sets a short infinitely looping buffer which buffer is all zero throughout the game work. Then it creates a number of other source and submix voices. Then upon game exit all those later voices get correctly destroyed by the games. But not that first looping voice. Then games attempts mastering voice deletion but that results in no-op due to the blamed commit (mastering voice is …
> Do not reference count audio engine from voices
