FNA-XNA/FAudio

src/FAudio.c, src/FAudio.h
COM AddRef/Release return the new reference count. Changing FAudio_AddRef/Release to do this as well prevents a duplicated reference counter in the C++ wrapper.
XAudio2Create allocates the XAudio implementation and initializes the engine. The COM-wrapper needs to be able to allocate without initializing in CreateInstance. I saw no other solution than to split off this functionality from FAudioCreate to another public function (FAudio_Construct).
=> Fix NULL pointer dereferences and improve compatibility with COM

src/FAudio.c
Fixes a tiny copy&paste error in a FAudioVoice_SetOutputMatrix assert.
=> Fix copy&paste bug

src/FAudio.c
With these changes applied the XAudio2 SDK sample XAudio2CustomAPO works with the FAudio COM DLLs.
=> Fix issues with EffectChain and effect-parameters.

src/FAudio.c, src/FAudioFX.c
I noticed that the latest FAudio doesn't compile with VS 2010 anymore while updating the COM-wrapper to work with VS 2010.
=> Fix compilation on VS2010

src/FAudio.c
This fixes a potential infinite loop in voice->src.bufferList after a FlushSourceBuffers and SubmitSourceBuffer combo.
=> Clear voice->src.bufferList when all buffers are removed

src/FAudio.c, src/FAudio_internal.h, src/FAudio_platform_sdl2.c
I cleaned up the WAVEFORMATEXTENSIBLE patch per your suggestions.
The 3 supported GUIDs are declared in the function itself, seemed like the easiest solution. They have no use in the rest of the library. In C99 it's possible to use the struct-initializer directly as an argument to memcmp but that won't work with VS2010.
=> Support WAVEFORMATEXTENSIBLE formats with a standard PCM subformat

src/FAudio_internal.c
While working on PR #15 I noticed submix voices with more than 1 channel did not play back correctly. The sound seems stretched out and choppy. You can reproduce the issue with the extended testreverb utility from PR #15. Just choose stereo sound, you don't have to enable the reverb effect.
This small change fixes the issue and does not seem to cause any other problems.
=> Fix multichannel submix voices

src/FAudio.c, src/FAudioFX.c, src/FAudio_internal.c, src/FAudio_internal.h, utils/testreverb/audio.cpp, utils/testreverb/audio.h, utils/testreverb/audio_faudio.cpp, utils/testreverb/audio_xaudio.cpp, utils/testreverb/testreverb.cpp
This fixes the issue we noticed when testing PR #12 with 5.1 surround sound.
As you predicted most of the work was in SetEffectChain and ProcessEffectChain. In addition to SetOutputMatrix I also had to touch SetOutputVoices and change the order of things that depend on the number of output channels in the Create...Voice functions.
SetEffectChain now validates the new effect chain and changing the effect chain is supported. As the last step it checks if in-place processing is supported by the effect at all and if it's possible in the current configuration.
ProcessEffectChain alternates between a 'global' effectChainCache and the original buffer when in-place processing isn't possible to allow longer chains.
To test this I extended the testreverb utility with a submix voice and the ability …
=> Enhance effect chain support in FAudio

src/FACT.c, src/FACT_internal.c, src/FACT_internal.h
Implement attack/release RPC similar to C# FNA XACT implementation.
For attack envelopes:
- Simply compute the time into the attack envelope.
For release envelopes:
- When creating a cue instance scan each tracks Release RPC channels to compute an upper bound on how long the sounds release can be. This is an over simplification as it doesn't take into account which tracks were playing at the time of a stop as authored state change. In the worst case it just means that the cue becomes fully silent and stays in the Stopping state longer than it needs to.
- When the sound is stopped as authored, put the sound into a special release state using the computed maximum release time.
- When in the release state, compute the time into the release envelope and keep playing and processing the RPC …
=> RPC Attack/Release

cpp/README.md, cpp/scripts/cross_compile_32, cpp/scripts/cross_compile_64
* fix typo in the documentation 
* tweak wrapper cross-compilation scripts: use `return` instead of `exit` to avoid killing the shell on error handling when sourced.
=> Minor tweaks

src/FAudio.c, src/FAudio_internal.c, src/FAudio_internal.h
This prevents performance degradation with applications that use large numbers as stage identifiers.
=> Store submix voices in a linked list sorted by ProcessingStage.

src/FAudio_internal.h
ecadcb7c652b3a90bd78cb1e3091b33a83a198ff broke compilation of utils on Linux. At least it did for me with GCC 7.3.
=> GCC utils fix

src/FAPOFX.c, src/FAPOFX.h, src/FAPOFX_echo.c, src/FAPOFX_eq.c, src/FAPOFX_masteringlimiter.c, src/FAPOFX_reverb.c, src/FAudio_internal.c, src/FAudio_internal.h, tests/FAudio_compat.h, tests/Makefile, tests/xaudio2.c
This adds a couple of behavior changes to pass the tests, and then imports the Wine test suite in a new subdir, `tests/`. Its makefile supports building a Windows executable, to verify the behavior of Microsoft's implementation, and includes a compat header that mostly #defines XAudio2 symbols into FAudio symbols, to verify FAudio's behavior against the tests.
Note that the CLSIDs commit will change the default CLSID value in the FAPO's properties struct.
=> Import wine tests

cpp/README.md
triple \` are used for multi-line code segments. For inline code (or
variables) should be highlighted with a single \`
Also remove trailing spaces, invisible, but `git` doesn't like them
=> reformat README of cpp

Makefile, src/FAudio.c, src/FAudio_internal.c, src/FAudio_internal.h
A couple possibly controversial points. First we remove -pedantic to get rid of some useless compiler warnings. Next we create a new define, FAUDIO_RELEASE, to make compile-time decisions about optimizations. Finally this creates a global debug config struct so we don't need to dig up FAudio pointers in every function we want to write some logging from.
I skipped a lot of the granularity from the xaudio2 specification. I don't see most of that being useful in practice, and even MSDN says that it actually only supports the ERRORS mask. If we need more complicated functionality, that can be added later, I think.
I added a couple of useful debug messages around source voice creation and buffer consumption behavior.
=> Debug logging take 2

src/FAudio_internal.h
Simple fix when building with Visual C, which doesn't support `__attribute__`.
There's also (AFAIK) no drop-in replacement that'd mimic `format`.
=> Disable __attribute__ on FAudio_debug_ for MSVC

extensions/EngineProcedureEXT.txt, src/FAudio.c, src/FAudio.h, src/FAudio_internal.c, src/FAudio_internal.h
You can view the accompanying Wine changes at https://github.com/aeikum/wine/commits/engineproc
=> RFC: Add new entry point for clients to wrap the engine procedure

CMakeLists.txt, utils/wavcommon/wavs.cpp
Instead of variables use target_sources to add source files to an existing target.
Support multiple versions of SDL2 imported targets
Edit: Hope the spaced instead of tabs don't shock or anger you :see_no_evil:
=> CMake modern target usage

src/FAudio_internal.h, src/FAudio_platform_sdl2.c
This fixes audio in WWE2k19, which first opens an 11kHz xaudio device, and then a separate 48kHz device and expects low latency on the latter.
This removes the global tracking of platform devices and instead tracks them in the FAudio object. This shouldn't break any external platform backends(?), but they might want to change to use the new platform pointer instead of a global list, for consistency.
The game uses GetState to maintain 4 buffers in the queue, so this debugging was useful there.
=> [On Hold] Allow multiple SDL handles per device

src/FAudio_internal.c
Hellblade: Senua's Sacrifice mixes into the output buffer instead of
ovewriting it.
=> Zero output buffer before calling FAPO::Process

CMakeLists.txt
On mingw-w64 cross compilation $CMAKE_INSTALL_LIBDIR is set to an absolute
path. Work around that by hard coding the directories on windows
=> cmake: use GNUInstallDirs, except for windows

cmake/modules/FindFFmpeg.cmake
- fix detection whether FFmpeg_INCLUDE_DIR is set by user
- be more restrictive where to search for the include/library when hint
is set
- when hint is set and a include path was found, then instruct
find_library to search at the provided paths first
this was an issue if ffmpeg is installed as system package. The user defines FFmpeg_INCLUDE_DIR, the include dir was found, but the libraries are taken from the system. This could lead to a hard to decode linker error (or maybe even runtime error)
=> cmake: prefer user ffmpeg over system ffmpeg

src/FACT_internal.c
The root of this issue was that FAUDIO_END_OF_STREAM wasn't reliable getting set and used to guard which callback should be called (EndOfBuffer or EndOfStream).  This resulted in cases where FACT_STATE_STOPPED wasn't being transitioned to, leading to pre-loading the next wave not happening.
The symptom is that the first track in the PlayWave event would play, but then would remain silent afterward never ending.
Non-streaming sounds do not encounter this issue since they always process and a single big enough buffer at once.
I put an assert in an old code path that I don't think is necessary anymore since the callback will only be called when there is work to do.
=> Fix PlayWave variations

cmake/install_shared_libs.cmake
Hit a CMake error building the native dlls following the CMake requirement downgrade aecb21034718abcea6115bd2e4853de6913b6643
https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/VariablesListsStrings#using-cmake-regexps
```
CMake Error at cmake/install_shared_libs.cmake:45 (string):
Syntax error in cmake code at
FAudio/cmake/install_shared_libs.cmake:45
when parsing string
\.(dll.a$|lib$)
Invalid escape sequence \.
Call Stack (most recent call first):
CMakeLists.txt:140 (install_shared_libs)
```
Build logs: git version is shown under 
```
==> Starting pkgver()...
==> Updated version: faudio-wrappers-git r${commitnumber}.${commitref}-1
```
5056ea9 build https://gitlab.com/archlinux-packages-johnth/mingw-w64-faudio-git/-/jobs/162963157
aecb210^ (5736333) build …
=> Fix cmake REGEX escaped character; add second backslash

CMakeLists.txt
On my system, SDL2's CMake config file unconditionally sets
`SDL2_INCLUDE_DIRS` and `SDL2_LIBRARIES`. This causes problems building
FAudio reproducibly when SDL2 is installed locally.
=> Don't override user-defined SDL2 variables.

src/FAudio.c
- explicit cast from uint32_t to doube of parameter
- fix warning of function cast by putting brackets around the command
=> fix conversion warning

src/FAudio.c, src/FAudio_internal.c, src/FAudio_internal.h, src/FAudio_platform_sdl2.c
found some warnings, kept them in small commits to easier rebase an squash them (or remove if one isn't up to snuff)
=> Fix warnings

src/FACT_internal.c
=> internal: fix DOSWAP macros

CMakeLists.txt, utils/showriffheader/showriffheader.cpp
Add executable parsing and showing the RIFF header to make the comparion
of wav files easier.
This makes my life for comparing the original wav files and the ones dumped with the help of `DUMP_VOICES` enabled `testxwma` executable
https://github.com/FNA-XNA/FAudio/pull/131
edit: example
```
found 'RIFF' at: 0
RIFF:             |RIFF|52.49.46.46|0x46464952|1179011410|
ChunkSize:        | <  |8a.3c.02.00|0x00023c8a|    146570|
Format:           |WAVE|57.41.56.45|0x45564157|1163280727|
fmt:              |fmt |66.6d.74.20|0x20746d66| 544501094|
ChunkSize:        |2   |32.00.00.00|0x00000032|        50|
fmt AudioFormat:  |    |02.00      |    0x0002|         2| FAUDIO_FORMAT_MSADPCM
fmt NumChannels:  |    |02.00      |    0x0002|         2|
fmt SampleRate:   | +  |11.2b.00.00|0x00002b11| …
```
=> add util/showriffheader

utils/showriffheader/showriffheader.cpp
Fix the case when fmt subchunk-size == 16, then there is no cbSize
entry, instead the data subchunk can immediately start.
Encountered when parsing a PCM formated wav file
```
showriffheader FA_fmt_0x0001_Ensoniq-ESQ-1-Sympy-C4.wav
found 'RIFF' at: 0
RIFF:             |RIFF|52.49.46.46|0x46464952|1179011410|
ChunkSize:        |*   |2a.8c.0f.00|0x000f8c2a|   1018922|
Format:           |WAVE|57.41.56.45|0x45564157|1163280727|
fmt:              |fmt |66.6d.74.20|0x20746d66| 544501094|
ChunkSize:        |    |10.00.00.00|0x00000010|        16|
fmt AudioFormat:  |    |01.00      |    0x0001|         1| FAUDIO_FORMAT_PCM
fmt NumChannels:  |    |02.00      |    0x0002|         2|
fmt SampleRate:   |D   |44.ac.00.00|0x0000ac44|     44100|
fmt ByteRate:     |    |10.b1.02.00|0x0002b110|    176400| …
```
=> showriffheader: fix when fmt subchunk-size of 16

src/FACT_internal.c
When investigating the following wine issue
https://bugs.winehq.org/show_bug.cgi?id=38615
It's attempting to load older XACT files which is causing the demo to crash on startup.
The data is the size, so I'm assuming that extra flags are available for the newer XACT format.
I've also changed the return values from -1 to -4 for each return branch, so we can workout why a function failed from the wine side.
=> XACT support for xactengine 3.1

CMakeLists.txt, src/FAudio.c, src/FAudio_internal.h, src/FAudio_platform_sdl2.c
- use a single function to open the same file for the same format
- write extensible data if file format is extended
- open file once for each submitChunk
- use only SDL_RWops functions for file access
It's not creating working files. It creates readable headers for non-extended encodings (at least VLC recognizes the format, but is not able to load the files). Warframe uses ADPCM and WMAUDIO2. I unfortunately havn't found refernce files for these formats to trim the dumping to produce working wma files
Feedback and tips are very welcome
=> dump audio buffer to wav files

src/FAudio.c
This special handling is not needed anymore as WMAUDIO2 is converted to
FAUDIO_FORMAT_EXTENSIBLE by FAudio_CreateSourceVoice().
=> dump: remove extra WMAUDIO2 handling in file name creation

src/FACT.c
We need to variable to handle each of FACT_FLAG_NOTIFICATION_PERSIST types, but for now it good enough to not attempt to access members that possible invalid.
Would it be OK to put in the engine 
uint32 notication_flags  -- 0x01, 0x02, etc and
void * wb_context
variable for each type?
=> FACTAudioEngine_RegisterNotification handle FACT_FLAG_NOTIFICATION_PERSIST

src/FACT.c
Pac-man Museum demo requires the GetState returns PLAYING without the PREPARED flag.
=> Playing a Cue should remove the FACT_STATE_PREPARED flag

CMakeLists.txt
Over at https://github.com/RPCS3/rpcs3 we use FAudio in a submodule, but we only want to link statically.
We don't want to use the shared library because when you `make install` rpcs3 will conflict with Linux FAudio packages.
This PR keeps the default functionality of building shared libraries, but just adds the ability to build FAudio statically as well.
=> Allow for building a static library instead of shared

src/FAudio_platform_sdl2.c
This is to make it clear we are using the same Allocation/Free functions.  On first look, it appeared as if they where using the wrong Allocate/Fee functions until diving into the internal header to see that the FAudio_free points to SDL_free.
=> Use FAudio_malloc macro for memory allocations.

src/FAudioFX_reverb.c
Dragon Quest Builders 2 audio is broken because is uses a DecayTime of -0.f, and that causes infinite gain and NaN values creeping up the reverb buffer.
This could also be done in some XAPO_PROCESS_BUFFER_PARAMETERS params validation code, or before calling / within DspReverb_SetParameters.
=> Handle negative zero rt60_ms values.

cpp/xaudio2.cpp, cpp/xaudio2.h
This is the definition of `XAUDIO2_EFFECT_DESCRIPTOR` in my Windows 8.1 SDK:
```cpp
// Used in XAUDIO2_EFFECT_CHAIN below
typedef struct XAUDIO2_EFFECT_DESCRIPTOR
{
IUnknown* pEffect;                  // Pointer to the effect object's IUnknown interface.
BOOL InitialState;                  // TRUE if the effect should begin in the enabled state.
UINT32 OutputChannels;              // How many output channels the effect should produce.
} XAUDIO2_EFFECT_DESCRIPTOR;
```
=> Fix XAUDIO2_EFFECT_DESCRIPTOR::OutputChannels name

src/FAudio_internal.c, src/FAudio_internal.h
I figured out the Banished crash!! The game creates new source voices in one thread while the engine thread is mixing sources. This would cause the decodeCache to be reallocated near the end of FAudio_CreateSourceVoice, while the buffer was still in use (e.g. being written into by the gst decoding code). This patchset moves the source mutex unlocking around each callback invocation, instead of around the entire mixing procedure (see 0a7e525702cd21cfee39b9816a152a1ab25ae538), and then takes the lock when it tries to realloc the buffer.
The third patch was just something I noticed while working on this code; feel free to ignore it if it's not worth the noise.
=> Protect caches

src/FAudio_internal.c, src/FAudio_internal.h
Fix for the issue with reverb on source voices, as reported in #205.
The `BufferFlags` of the last output buffer of an effect chain are stored in the voice. This value is evaluated when there are no more buffers on a source voice with an effect chain. Do not exit `FAudio_INTERNAL_MixSource` if it was not a silent buffer.
I tried to implement it with minimal changes to `FAudio_INTERNAL_MixSource` to limit the impact of the changes. This does mean I chose to duplicate the PLAY_TAILS-code to clear the buffers and jump to `sendwork`.
Tested with `testreverb`, `testvolumemeter`, and Murder Miners to check for regressions. I don't own any of the games mentioned in #205 so I can't check if this fixes the reported stuttering issues.
=> Keep processing the effect chain until it generates a silent buffer.

src/FAudio.c, src/FAudio_internal.c, src/FAudio_internal.h, src/FAudio_internal_simd.c
The first commit removes a lot of the multiplications from the mixing functions. That speeds things up a little bit, but not very noticeably.
The second commit uses SSE to perform the attenuation, while we have at least four source channels remaining to pull from. It significantly improves performance and fixes the underruns for me in Beyond Two Souls. The game is kind of a special case in that it does a lot of mixing from 8-channel sources, which will hit the fast path very often.
=> Provide SSE generic mixing function

src/FAudio.c, src/FAudio_internal.c, src/FAudio_internal.h
First commit moves allocation of the resample cache into the mixer code, like you suggested (#215).
Second commit mirrors the submix voice mixing, where it holds sendLock through the whole mixing procedure. My motivation here was to protect access to resampleSamples, which otherwise could change mid-mix (I guess it still can via callbacks...).
Please review carefully, there's a lot of locks going on here, and it's possible I made a mistake. One open question is whether we should hold the bufferLock while calling the callbacks. We currently do, so I didn't change that, but I wonder if we should drop the lock?
=> Resample cache locks

src/FACT_internal.c
This allows xacteninge 2 series to use FAudio.
=> Allow Engine Initial to not have global settings

CMakeLists.txt
IMPORTED_TARGET was only introduced in cmake 3.6 and FAudio does not build with GStremer versions older than 1.9.2.
Fixes https://github.com/FNA-XNA/FAudio/issues/226
=> cmake: Fix compatiblity with older cmake versions.

src/FAudio.c, src/FAudio_internal.h, src/FAudio_platform_sdl2.c, tests/xaudio2.c
Adds a test for the value of the OutputFormat.SubFormat UUID on the results returned from IXAudio27_GetDeviceDetails and updates FAudio_PlatformGetDeviceDetails to always set this field to MFAudioFormat_PCM, mirroring the behavior of native xaudio2.7.  This fixes in-game audio in at least two Ubisoft games (Far Cry Primal and Watch Dogs).
Fixes ValveSoftware/proton#2425
=> Always set OutputFormat.SubFormat to MFAudioFormat_PCM in FAudio_PlatformGetDeviceDetails.

CMakeLists.txt, cmake/FAudio.pc.in, cmake/JoinPaths.cmake
Fixes https://github.com/FNA-XNA/FAudio/issues/224.
`JoinPaths.cmake` is modified from jsoncpp.
https://github.com/open-source-parsers/jsoncpp/commit/5be07bdc5e2d5b7715ecbc73749af3e625674dcb
I based the pc file off the copy installed in gentoo.
https://gitweb.gentoo.org/repo/gentoo.git/tree/app-emulation/faudio/files/faudio.pc?id=e0ec6727d673a6ac44c7ee7d82d2ebc609e1f511
=> cmake: Add a pkgconfig file.

tests/xaudio2.c
Got some errors compiling tests with commit 03114a7 where
it seems as DATAFORMAT_SUBTYPE_PCM will be declared twice.
DATAFORMAT_SUBTYPE_PCM is already declared as "extern" in
FAudio.h for FAudioGUID.
The tests compile and run ok with this patch.
Ref to my comment here: [https://github.com/FNA-XNA/FAudio/commit/03114a7f57cf7232d4088f7dcbbff3b3f7fdbe3f#commitcomment-44268929](https://github.com/FNA-XNA/FAudio/commit/03114a7f57cf7232d4088f7dcbbff3b3f7fdbe3f#commitcomment-44268929)
=> Fix compile error with tests

README, src/FAudio_platform_sdl2.c
Restore preprocessor macro introduced in:
Commit 7b0973e62c05 ("Warning for SDL <2.0.9")
and removed in:
Commit a0f859c761bb ("Enforce a quantum size measured in millisecon...")
to reduce confusion as to the compiler errors
Include the exact version number in the README and include a few common
distributions that contain at least the requisite version
The previous version contained an #ifdef for a Windows specific
preprocessor directive but it seems to be supported now in MSVC and
other noteworthy compilers:
https://docs.microsoft.com/en-us/cpp/preprocessor/hash-error-directive-c-cpp
https://gcc.gnu.org/onlinedocs/cpp/Diagnostics.html
https://clang.llvm.org/docs/UsersManual.html#controlling-diagnostics-via-pragmas
=> Increase verbosity of SDL dependency

src/FACT_internal.c
These seem to be the formulas XACT is using, or as close as I can find by comparing the curves visually.
Why is there no sin or cos in SinCos? We may never know. It does make a perfectly circular arc though.
=> More accurate Fast/Slow/SinCos RPC curves

src/XNA_Song.c
`stb_vorbis.h` can use `fopen_s` when compiled in certain environments. `XNA_Song.c` redefines `fopen`; this PR adds the missing `fopen_s` definition.
=> Fix fopen_s not being defined for stb_vorbis

csharp/FAudio.cs, include/FAudio.h, src/FACT.c, src/FACT_internal.c, src/FAudio.c, src/FAudio_gstreamer.c
Compared to #66, this is no longer "initial" and it's no longer taking stupid shortcuts.
_\*breathes in\*_
- `gst-libav` ships with `avdec_xma2` (citation needed). While we could [wait for every distro under the sun to expose proper sink caps,](https://gitlab.freedesktop.org/gstreamer/gst-libav/-/merge_requests/124) I've taken the creative liberty to add an optional `autoplug-factories` handler with some dynamic mimetype shenanigans for that specific factory.
- I've added `FAudioXMA2WaveFormat` as FFmpeg currently accepts (but doesn't fully respect) XMA2 extra data.
- XMA2 wave data no longer gets packed into `FAudioWaveFormatExtensible`. Goodbye, broken shortcuts!
- To handle the multitude of wave formats more easily, I've added `FAudioAnyWaveFormat` as an union of all wave formats.
- …
=> Basic FUNCTIONAL XMA2 support

src/FACT_internal.c
This PR fixes an oversight from #247: https://github.com/FNA-XNA/FAudio/pull/247/files#diff-5e9d130bd3d0e6c75ac5c66ff39127498b853b107dbf8d5e1882ba3478e64ef9L1891-R1891
I've mistakenly removed `0x3` (xWMA) from the check when `0x1` (XMA2) was supposed to be removed.
=> Fix WMA BufferWMA bug introduced with XMA2 patchset

src/FACT.c
I've encountered a game with looping sounds yet loop regions with a length of zero. Apparently this is valid...
=> Loop region length can be 0

src/FAudio_platform_win32.c
Didn't take long to get into trouble.
=> Use lstrcpynW instead of memcpy on Win32.

src/FAudio_platform_win32.c
This fixes WMAV2 which was outputting garbage on Windows. I can now play `ergon.xwma` using `testxwma.exe` as well as other WMAV2 streams.
=> Fix incorrect value for MF_MT_AUDIO_AVG_BYTES_PER_SECOND.

src/FAudio_internal.h
MinGW somehow seems to get it from somewhere else but that's not right
and Wine headers (or MSVC) don't.
=> Include malloc.h for alloca on Win32 platform.

src/FAudio.c
This stops a crash running Monkey island 2 under wine.  It happens to have a WMA buffer with the FAUDIO_FORMAT_EXTENSIBLE type.
=> Dont assert on WMA buffer and FAUDIO_FORMAT_EXTENSIBLE type

src/FAudio.c
Commit b5916945b90d ("Dont assert on WMA buffer and
FAUDIO_FORMAT_EXTENSIBLE type") introduced unbalanced parentheses,
which breaks builds using HAVE_WMADEC.
Given the change made in the aforementioned commit, this balances
parentheses by adding a third closing parenthesis after the reworked
conditions.
Signed-off-by: Stephen Kitt <steve@sk2.org>
=> Fix unbalanced parentheses in FAudio.c

src/FAudio_platform_win32.c
Set thread names for the Win32 platform.
I've tested this in Wine, but not on actual Windows.
=> Set thread names for the Win32 platform

src/FAudio_platform_win32.c
Far Cry 4 expects it, and testing shows that it's apparently the case on Windows (https://testbot.winehq.org/JobDetails.pl?Key=104269) even though WASAPI default mix format is IEEE_FLOAT.
=> Return a PCM format by default in Win32 GetDeviceDetails

csharp/FAudio.cs
This is to allow writes to a location beyond the beginning of the float[] array.
=> Add overload of stb_vorbis_get_samples_float_interleaved with float pointer

src/FAudio_platform_win32.c
Instead of copying garbage when `output_pos < samples_pos` and `output_pos - samples_pos` overflows, as they are both unsigned.
=> Clear the end of WMA buffer when decoded output is too short.

src/FAudio_platform_win32.c
Behaviour with the SDL2 backend is to return 0 here, and the managed side throws a `NoAudioHardwareException`
=> Fix hard-crash when no audio devices are present on win32

src/FAudio_platform_win32.c
When using the win32 backend, and the primary sound output device returns a `WAVEFORMATEX` (eg `FAUDIO_FORMAT_IEEE_FLOAT`) from `IAudioClient_GetMixFormat`, no speaker mask gets set. This causes `F3DAudioInitialize8` to fail an assertion that there must be a non-zero speakermask.
```
Assertion failed: speakerMaskIsValid == 1 && "SpeakerChannelMask is invalid. Needs to be one of" " MONO, STEREO, QUAD, 2POINT1, 4POINT1, 5POINT1, 7POINT1," " SURROUND, 5POINT1_SURROUND, or 7POINT1_SURROUND.", file C:\Users\covers1624\Programming\tModLoader\FNA\lib\FAudio\src\F3DAudio.c, line 133 
```
I used the fallback based on number of channels, so 3d audio should work correctly most of the time.
=> Set fallback dwChannelMask in device details for non-extensible formats

src/FACT.c
Ensure all fields for the WAVESTOP notification are filled in correctly. 
A NULL context is valid, so always copy it, so it's a know value.
=> Full all wave fields for WAVESTOP Notification

src/FACT.c, src/FACT_internal.h
The notifications are not sent immediately, but pushed to a queue
and sent at the next DoWork() call. This seems to correspond to what
happens on Windows.
=> Send WAVEBANKPREPARED notifications.

src/FAudio_platform_win32.c
The SDL2 implementation of `GetExitCodeThread` allows passing `NULL` to ignore the exit code. The WINAPI function does not.
=> Fix access violation on win32 thread shutdown

README, src/FAudio_platform_sdl2.c
- 2.1 and 4.1 audio is now supported
- DirectSound is now prioritized over WASAPI
- The PulseAudio samples hack has been removed
- The non-power-of-two samples hack for Emscripten/OSS has also been removed
- GetDeviceDetails(0) now uses SDL_GetDefaultAudioInfo, obsoleting our hack
Trust me, you want _all_ of these fixes. Update your SDL version!
=> Update to SDL 2.24.0.

src/FAudio.c
There isn't a point in getting the details if we are just going to ignore them later on.
=> Only get device details if required.

src/FACT.c
IXACT4Engine::ShutDown states that it Flushes and unregister's all notifications.
=> Purge and clear notifcations on ShutDown

CMakeLists.txt
usleep() from unistd.h requires _BSD_SOURCE (required on musl libc) (+_DEFAULT_SOURCE for glibc)
=> CMake: add feature macros for usleep for tests

src/FACT_internal.c
This is one step in supporting older versions.
=> ParseSoundBank: Use Offset where possible.

src/FAudio_internal_simd.c
There are no SSE2 and NEON on PowerPC, for obvious reasons.
=> Unbreak build on Darwin PowerPC

src/FACT_internal.c
In xactengine 2.5, the extra field HeaderVersion was added.
=> Support all WaveBank versions

src/FAudio_platform_win32.c
The extra codec data is not being passed by the METAL GEAR SOLID 3: Snake Eater - Master Collection Version. I've tried to make it work:
```diff
diff --git a/libs/faudio/src/FAudio.c b/libs/faudio/src/FAudio.c
index 7d34b666535..d235fd44a1a 100644
--- a/libs/faudio/src/FAudio.c
+++ b/libs/faudio/src/FAudio.c
@@ -297,7 +297,7 @@ uint32_t FAudio_CreateSourceVoice(
pSourceFormat->wFormatTag == FAUDIO_FORMAT_WMAUDIO3   )
{
FAudioWaveFormatExtensible *fmtex = (FAudioWaveFormatExtensible*) audio->pMalloc(
-        sizeof(FAudioWaveFormatExtensible)
+        sizeof(FAudioWaveFormatExtensible) + pSourceFormat->cbSize
);
/* convert PCM to EXTENSIBLE */
fmtex->Format.wFormatTag = FAUDIO_FORMAT_EXTENSIBLE;
@@ -306,7 +306,7 @@ uint32_t FAudio_CreateSourceVoice(
fmtex->Format.nAvgBytesPerSec = …
```
=> Create fake codec data for WMA3

src/FAudio_platform_sdl2.c
This fixes sound playback on big-endian machines.
Fixes: #329
=> SDL: set the playback format with native endianness

include/FAudio.h, src/FAudio.c, src/FAudio_internal.c
Cosmoteer (Steam game id 799600) sometimes destroys a submix voice which is an output for another voice. That leads to use after free access in audio client thread performing mixing which leads to obscure random crashes.
MS docs [1] suggest that IXAudio2Voice::DestroyVoice fails in such a case ("If any other voice is currently sending audio to this voice, the method fails.").
I made a test on top of Wine xaudio2 tests which indirectly confirms that (attaching a patch). I don't immediately see a direct way to test if DestroyVoice actually failed or not as it doesn't return any status. However, I found that after successful voice destruction IXAudio2SubmixVoice_GetVoiceDetails() for that voice crashes on Windows and using this fact to probe for actual voice destruction (the first one in the …
=> Don't destroy voice when it is output to other voices

src/FAudio_internal.h
This is a followup on 81d5a24 (build: fix building with MSVC,
2024-03-07).
Fix the missing trailing _ in __attribute__ for
__attribute((aligned(x))).
=> build: fix __attribute__((aligned(x))) on gcc/clang

CMakeLists.txt, cmake/FAudio.pc.in, cmake/config.cmake.in
This is a followup on 81d5a24 (build: fix building with MSVC, 2024-03-07) and 68a555e (build: fix __attribute__((aligned(x))) on gcc/clang, 2024-03-09) for the purposes of creating a vcpkg FAudio port.
Add a `Requires.private: sdl2` to the pkgconf file for the SDL2 dependency when not using PLATFORM_WIN32.
Add the SDL2 dependency to the generated cmake config file when not using PLATFORM_WIN32 as well.
=> build: fix dependency on SDL2

src/FAudio_internal.c, src/FAudio_internal.h
This is an attempt to fix a Wine bug. Downstream PR: https://gitlab.winehq.org/wine/wine/-/merge_requests/5424
Deadlock was being caused by the fact that some private FAudio routines hold internal mutexes while calling application callbacks. This may result in a deadlock because app might have a huge global mutex that is locked both by callbacks and by some code that e.g. submits new buffers to XAudio.
=> Fix deadlock in voice callbacks

src/FAudio_internal_simd.c
I wrote this as a part of efforts to support ARM64EC in Wine. On ARM64EC, both `__x86_64__` and `__arm64ec__` macros are defined, so I reordered ifdefs to prioritize ARM checks.
=> faudio: Use NEON intrinsics on ARM64EC.

src/FAudio_platform_win32.c
And don't crash if the computer doesn't have any audio devices.
Fixes #347
=> win32: Always check the return value of GetDefaultAudioEndpoint

src/FAudio_platform_win32.c
Previously, we would crash when the audio device was disconnected.
=> [windows] Exit cleanly on audio device disconnect

src/FAudio_platform_win32.c
Previously, FAudio with `PLATFORM_WIN32` would only list the default audio device. This reworks the Faudio `PLATFORM_WIN32` code to enable access to every audio device on the system. In order to preserve the existing behavior (and Xaudio2 compabitility), the audio devices are re-ordered so the first device is always the default one.
In addition, this properly populates the `DisplayName` field in `FAudioDeviceDetails`. Previously, it was set to the device GUID.
Test: Local build with visualboyadvance-m
=> [windows] List all audio devices for Windows

CMakeLists.txt, cmake/config.cmake.in
Export the FAudio::FAudio-shared target when building a shared library and the FAudio::FAudio-static target when building a static library to separate target files so that both can be installed at the same time.
Alias FAudio::FAudio to the shared library if it is installed and the static library otherwise in the Config.
=> build: separate shared and static import targets

src/FAudio_platform_sdl3.c
The return values of these functions differ:
https://wiki.libsdl.org/SDL3/SDL_ReadIO
https://wiki.libsdl.org/SDL2/SDL_RWread
SDL2 returns the number of objects read, while SDL3 returns the number of bytes.  So, divide by the count of objects?
=> Account for difference in SDL2/SDL3 IO return values

.github/workflows/ci.yml
It would be nice to figure out how to spit out a universal dylib for MacOS, but I'm not familiar enough with how that works. It would also be nice to figure out how to upload the release artifacts to the release page automatically when a release is tagged, but I'm not sure how to test that.
=> Add SDL3 to CI and upload build artifacts

csharp/FAudio.cs
Just enough to be able to write your own spectrum analyzer.
It would be nice if FAudio took ownership of the registration properties passed in, so I could make them a `ref T` argument instead of an IntPtr you have to malloc and leak.
=> Add C# wrapper for part of FAPO and FAPOBase APIs

include/FAudio.h, src/FAudio.c
This quantum is required for certain APOs, and enforcing this flag maintains better compatibility.
=> Fixed documentation / assertion preventing using FAUDIO_1024_QUANTUM.

CMakeLists.txt, csharp/FAudio.cs, extensions/CollectorEXT.txt, include/FAudioFX.h, src/FAudioFX_collector.c, visualc-gdk/FAudio.vcxproj, visualc/FAudio.vcxproj
Simple and easy to use. Hand it a ring buffer and it will fill it with mono samples (so you don't need to think about how many channels there are), and you can feed that into an FFT or something else in order to do a realtime spectrum analyzer, etc.
I previously did this with a custom callback from outside but Collector makes it much easier and eliminates the possibility of crashing/hanging the mixer thread.
=> Add FAudioCreateCollector to create a FAPO that captures samples into a buffer

src/FAudio_platform_win32.c
That fixes Space Engineers under Proton which was randomly crashing due to memory corruption.
=> Fix zeroing cache in FAudio_INTERNAL_DecodeWMAMF()

CMakeLists.txt
With this PR I suggest making installation optional, and defaulting to OFF when using FAudio as a dependency.
This is similar to what SDL does and makes it easier for dev users relying on FAudio as a dependency - probably most of them.
=> [CMAKE] Add an option for installation

src/FAudio_platform_sdl3.c, src/FAudio_platform_win32.c, src/FAudio_platform_win32_wmadec.c
Fix some warnings for MSVC. Mostly by type casts. Convert one `fopen()` call to `fopen_s()` with error handling and one double -> int conversion for a buffer size with `ceil()`.
=> build: fix warnings for MSVC
